server:
  port: 0

spring:
  application:
    name: company-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

management:
  endpoints:
    web:
      exposure:
        include: env