spring:
  application:
    name: company-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URI:http://localhost:8888}

management:
  endpoints:
    web:
      exposure:
        include: env, health, configprops

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10