spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**

        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/company-service/**

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: env, health, configprops

logging:
  level:
    org.springframework.cloud: DEBUG