server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Airat102vb/demo-spring-cloud-configs.git
          clone-on-start: true
          default-label: main
          search-paths:
            - '{application}-{profile}'
      discovery:
        enabled: true

logging:
  level:
    org.springframework.cloud: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: env, health

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true